version: "3"
services:
  api:
    build: ./api
    tty: true
    command: sh -c "npm run start:dev"
    ports:
      - "8000:3000"
    volumes:
      - ./api:/usr/src/app
  mysql:
    image: mysql/mysql-server:5.7
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - '3306:3306'
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - /var/lib/mysql
    env_file:
      - ./.env
  client:
    build: ./client
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./client:/usr/src/app
    command: sh -c 'npm run dev'
    ports:
      - '3000:3000'
    tty: true
  nginx:
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    tty: true
    restart: always
    depends_on:
      - client
      - api
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
